### PR TITLE
Rework how and where we extract/install openstack tarballs

### PR DESCRIPTION
**Pull request by vuntz**
This is a bit cleaner now, and we have some "marker files" that can be removed to forcefully reinstall things.

### CODE REVIEW

**Comment by aplanas** [comment]
looks very good to me (but not tested): +1

**Comment by vuntz** [comment]
@aplanas yeah, sorry for the not-fun commit history here; I tried to clean it up by squashing things, but it created conflict every time so would have taken a bit too logn to get right :/

**Comment by ovisan** [comment]
:+1: tested

**Comment by vuntz** [comment]
We tested the change, it works.

**Pull request merged**
